spring:
  application:
    name: FOOD-CATALOG-SERVICE

  datasource: 
    url: jdbc:mysql://localhost:3306/restaurant_db
    username: restaurant_user
    password: restaurant_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9093
  servlet:
    context-path: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8075/eureka/

logging:
  level:
    root: INFO
    '[com.pushpak.restaurantlisting]': DEBUG
  